import React from "react";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { CartProductContext } from "@/context/CartProductContext";
import { SiteBlob } from "./components/SiteBlob";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";


export const metadata = {
  title: "Skincare Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <CartProductContext> 
          <ThemeProvider>
            <SiteBlob/>
            {/* <Navbar/> */}
            <main>{children}</main>
            {/* <Footer/> */}
          </ThemeProvider>
        </CartProductContext>
        </body>
    </html>
  );
}
