import React from "react";
import "./style/globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { CartProductContext } from "@/context/CartProductContext";
import { AuthProductContext } from "@/context/AuthContext";


export const metadata = {
  title: "Skincare Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AuthProductContext>
        <CartProductContext> 
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <main>{children}</main>
          </ThemeProvider>
        </CartProductContext>
        </AuthProductContext>
        </body>
    </html>
  );
}
