import React from "react";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import {SideNavBarContext} from "@/context/SideNavBarContext"
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Skincare Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SideNavBarContext> 
          <ThemeProvider>
            <Navbar/>
            <main>{children}</main>
            <Footer/>
          </ThemeProvider>
        </SideNavBarContext>

       
      </body>
    </html>
  );
}
